### ISSUE TITLE
Turn Bakery off

### ISSUE THREAD

**Issue by serundeputy** [backdrop-ops/localization#10]
I added a new user to the localization site: `robertgarrigos` , but he could not sign in due to bakery.

I believe that we do not have bakery working correctly across sites right now so I've turned it off. I don't think that has adverse effects on anyone, but if it does we can turn it back on.

Just leaving a paper trail here.  Just give a thumbs up/agree or down/disagree.

**Comment by olafgrabienski** [comment]
Agreed. Will test later if my account still works.

**Comment by olafgrabienski** [comment]
Ok, the account still works.

**Comment by olafgrabienski** [comment]
If we plan to re-enable Bakery module, we should have another look at #11.
