### ISSUE TITLE
cannot login with bakery on

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-ops/localization#11]
@serundeputy added me to localize.backdrop and I could not log in until he turned off bakery (which, btw, I have no idea what it is).

Trying to log into localize.backdrop with user name and pass provided it redirected me to https://backdropcms.org/bakery/login with an access denied message.

Also, before using the password provided, I tried with the reset link sent by the system. It got me also to the backdropcms access denied page

**Comment by serundeputy** [comment]
yep; so as stated; currently bakery is off: https://github.com/backdrop-ops/localization/issues/10

**Comment by robertgarrigos** [comment]
is it on again? I have not access to the translate page when logged in, but when logged out

**Comment by serundeputy** [comment]
No it is still off as far as I know. I'm on my phone I'll do a proper check
later today

**Comment by olafgrabienski** [comment]
@robertgarrigos Bakery is still off (and I guess the issues with it are not easy to fix). Re the translate page I've enabled two permissions for authenticated users which before were only enabled for anonymous users: `access localization community` and `browse translations`. The latter should give you access even when you're logged in.

**Comment by robertgarrigos** [comment]
Yep, fixed with the permission set.

**Comment by olafgrabienski** [comment]
So, the issue is fixed for the moment, as long as Bakery remains turned off. We can reopen it if we plan to use Bakery again.
