### ISSUE TITLE
Install Organic Groups + required modules

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#12]
To get the groups functionality for translation teams working, we need a couple of Drupal 7 modules on the site, primarily Organic groups plus some required modules.

@serundeputy Are you up to install the following modules for the translation server? (Installation via the user interface is asking for FTP credentials.)

Needed Module / version by the time of writing:

- [x] Chaos tools (ctools) 7.x-1.14
- [x] Entity API (entity) 7.x-1.9
- [x] Entity Reference (entityreference) 7.x-1.5
- [x] Organic Groups (og) 7.x-2.10
- [x] Rules 7.x-2.11
- [x] Views 7.x-3.20 
- [x] Views Bulk Operations (vbo) 7.x-3.5

@robertgarrigos tested the modules and their configuration on his own test site. See details on https://github.com/backdrop-ops/localization/issues/7#issuecomment-410491245 and following comments:

> Also, something we could add to the website is the organics groups module. It is a good way of managing teams and, most important, to have some specific language information made by the team itself. This is how localize.drupal.org works, in fact. (...)

> I had installed Organic Groups in my testing site (https://traduccio.backdrop.cat/) and have documented the setting process. It looks like it's working quite well, but I had to change roles, as they are mainly managed by the og module. So, there is now a site wide role for a groups manager, which is language group manager. This role assigns other og roles, mainly a group administrator, who creates any group related content (pages or posts) and a group description. Any registered user can join any group and add translation suggestions, which are approved, or not, by the translator supervisor. (...)

> Added some functionality about notification of new members. I added also rules module and tuned the permissions. (...)

**Comment by serundeputy** [comment]
@olafgrabienski I can install; I won't be able to deploy (no access)
Once installed i'll update the issue and assign to Jen.

**Comment by serundeputy** [comment]
@olafgrabienski I've added the requested modules and a `localization_core` custom module to handle enabling them.

Once this is deployed visit: `/admin/modules` and enable the `Localizaton Core` module and that should enable all the requested modules.

@jenlampton please deploy when you get a chance.

thanks.

**Comment by olafgrabienski** [comment]
Thanks @serundeputy, very kind! Looking forward to deployment!

**Comment by jenlampton** [comment]
on it!

**Comment by jenlampton** [comment]
Deployed and enabled Localization Core.

**Comment by olafgrabienski** [comment]
Thank you!

**Comment by robertgarrigos** [comment]
@olafgrabienski could you add the catalan language? I would use it as a test when ready if that's ok. thanks

**Comment by olafgrabienski** [comment]
@robertgarrigos Sure, will add it! I hope to start with the configuration tasks today.
