### ISSUE TITLE
File upload fails: Request Entity Too Large

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#16]
When I try to upload a (not very large) `.po` language file on `translate/languages/de/import`, the upload fails and I see the error "413 Request Entity Too Large".

The maximum allowed size for uploads is 64 MB but the error seems to occur with files larger than 1 MB.

**Comment by olafgrabienski** [comment]
Due to the error page the server runs on `nginx/1.13.12`. I've made a quick research and found out that not only PHP but also Nginx can be set to allow a maximum size. Nginx uses `client_max_body_size`, and I guess its current value is too low.

**Comment by olafgrabienski** [comment]
@larsdesigns has checked the server's NGINX and PHP settings in the probably related issue #14. At the moment it remains unclear why it's not possible to upload files larger than 1MB.

**Comment by jenlampton** [comment]
From https://localize.backdropcms.org/admin/reports/status/php It looks like `upload_max_filesize` is 64M. ~~I'll log into the server and see if I can adjust it.~~

edit: I just re-read the thread. The error pops up with smaller files? hrm... looking into `client_max_body_size` setting.

**Comment by jenlampton** [comment]
okay, I've attempted to set `client_max_body_size` to `200M` in both the server context for localize.backdropcms.org. @olafgrabienski can you please try again and let me know if it's any better now?

**Comment by olafgrabienski** [comment]
@jenlampton Seems that the new settings did the trick, I was able to upload a language file larger than 1MB, thank you very much!

**Comment by jenlampton** [comment]
Nice!
