### ISSUE TITLE
German: Attribute translations to Multiple contributors

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#18]
When imported translations were worked on by a team of people -- which is often the case, especially because many Backdrop language files were built using a Drupal language file -- , it is recommended to not attribute the translations to a personal username. To allow that, there is a user account called "Multiple contributors" on the translation server.

When experimenting with the translation server and the German language, nearly all German translations were attributed to my personal user account. So far, I've not discovered an option to *change* all these attributions to the "Multiple contributors" account. If we don't find such an option, I'd suggest to change the value directly in the database. 

We should do this however not before #16 is fixed (to be sure that we can restore database backups easily).

**Comment by olafgrabienski** [comment]
On my local server I've tried to reimport a `.de.po` file with one translation string and to attribute it to "Multiple contributors" choosing the respective radio button on the import page. Unfortunately, I got the message "1 duplicate translation not saved", and the string remains attributed to my personal user account.

**Comment by jenlampton** [comment]
German translations are now attributed to multiple:
https://localize.backdropcms.org/translate/languages/de/translate

**Comment by jenlampton** [comment]
Closing in favor of https://github.com/backdrop-ops/localize.backdropcms.org/issues/34
