### ISSUE TITLE
Admin menu of localization server disappears

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#2]
After logging in to https://localize.backdropcms.org I see the *Administration menu*, but when I open any page on the site, it disappears. When I clear the cache via `admin/config/development/performance`, the Admin menu shows up again, but reloading the page or opening another one makes it disappear again.

**Comment by serundeputy** [comment]
I turned off `cache admin menu locally` on `admin/config/administration/admin_menu` in the Performance vertical tab. That seems to help.

@olafgrabienski if you can confirm let's close this issue.

**Comment by olafgrabienski** [comment]
Yeah, can confirm that it helps, works fine now!
