### ISSUE TITLE
Install Honeypot

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#24]
From issue #21:

There are many fake users creating accounts on the localization server (...). To prevent new fake accounts, I suggest to install and configure the Honeypot module.

**Comment by olafgrabienski** [comment]
@jenlampton Can you install the *Honeypot* module on the localization server?

**Comment by jenlampton** [comment]
Done :)

**Comment by olafgrabienski** [comment]
Thank you!
