### ISSUE TITLE
Improve release order of downloads

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#28]
The items in the "Top downloads" list of a translation group ([example](https://localize.backdropcms.org/translate/languages/ca)) seem to be ordered by "Version". The sort criteria (ascending alphabetical, or numerical?) doesn't present Backdrop's semantic version releases in the correct order.

Actual behavior:

1.10.2
1.11.5
1.12.2
1.6.4
1.7.4
1.8.4
1.9.6

Expected behavior:

1.6.4
1.7.4
1.8.4
1.9.6
1.10.2
1.11.5
1.12.2

Or even better:

1.12.2
1.11.5
1.10.2
1.9.6
1.8.4
1.7.4
1.6.4

**Comment by olafgrabienski** [comment]
IIRC, the list isn't a view. To fix the order, we could try to adapt the module code or to build a custom view.

**Comment by olafgrabienski** [comment]
The order issue occurs also on the page *Backdrop CMS translation downloads*, https://localize.backdropcms.org/translate/downloads.

**Comment by olafgrabienski** [comment]
> we could try to adapt the module code or to build a custom view

I guess there is no *Views* integration for the language files, and I've not the skills to look for other methods to change their order.

@jenlampton Can you have a look at the download lists on pages like https://localize.backdropcms.org/translate/languages/ca and https://localize.backdropcms.org/translate/downloads to see if / how we can fix the order? (Assigning the issue to you.)

**Comment by jenlampton** [comment]
Sure, I'll have a look today.

**Comment by jenlampton** [comment]
Fixed! 
See https://localize.backdropcms.org/translate/downloads?project=backdropcms
And https://localize.backdropcms.org/translate/languages/ca

Let me know if you see anywhere else where the sort order needs to be updated, I had to do each of these individually.

**Comment by olafgrabienski** [comment]
Thank you very much, looks good!
