### ISSUE TITLE
Install Module Filter and Backup and Migrate

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#3]
During configuration of the translation server I'd like to use [Module Filter](https://www.drupal.org/project/module_filter) and [Backup and Migrate](https://www.drupal.org/project/backup_migrate). Installation via the GUI fails because of missing FTP credentials. @serundeputy Would be nice if you could install the modules, thanks!

**Comment by serundeputy** [comment]
@olafgrabienski i've added the modules.

You need to conf backup_migrate; please make sure it is not storing backups in web accessible places!

~Geoff

**Comment by olafgrabienski** [comment]
Thanks a lot, @serundeputy! Re backup_migrate: no configuration needed, I'll store backups only locally.

**Comment by serundeputy** [comment]
ahh; great
