### ISSUE TITLE
Provide a UI to change attribution for an entire language to "Multiple Contributors"

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/localization#34]
I would like to build a UI so that people can easily adjust attribution to the "Multiple Contributors" user account.

**Comment by olafgrabienski** [comment]
Another idea: change the default option. When I go on an import page, the default is "Attribute import to Yourself (Olafski)", it should be "Multiple contributors" in my opinion.

**Comment by jenlampton** [comment]
done! see https://localize.backdropcms.org/translate/languages/fr/import

**Comment by jenlampton** [comment]
Can do.
