### ISSUE TITLE
Enable personal contact form

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#36]
By @robertgarrigos via email:

> I cannot see any way in localize.backdropcms.org to contact group members other than creating a group post. It might be a good idea to enable the personal contact tabs.

Indeed, that's a good idea, I'm going to enable the personal contact forms.

**Comment by olafgrabienski** [comment]
I've enabled the personal contact forms. They seem to work but not with the role "Authenticated User". Here's what I've done:

- Enabled *Contact* module.
- Permissions > Contact > Use the site-wide contact form: Disabled for all roles
- Permissions > Contact > Use users' personal contact forms: Enabled for *Authenticated User*
- Permissions > User > View user profiles: Enabled for *Authenticated User*

@robertgarrigos Can you test the form as a *Groups manager*? And do you have any idea what's missing for *Authenticated user*?

**Comment by robertgarrigos** [comment]
Do you have your contact form enabled in your profile? I cannot access it. Can you access mine on https://localize.backdropcms.org/user/MY-ID/contact ??

**Comment by olafgrabienski** [comment]
No, it wasn't enabled in my profile, now it is! Want to try again?

I wasn't aware of the setting in the profile. Seems that it is disabled by default. So, to make contact to group members possible, I guess we need to ask new members to enable the contact form. Other ideas?

**Comment by robertgarrigos** [comment]
ok. yep, I can see yours now. Thanks! Sent a test message also.

**Comment by robertgarrigos** [comment]
Now, could we have this enabled as default for new users? I think it would be better.

**Comment by olafgrabienski** [comment]
> Now, could we have this enabled as default for new users? I think it would be better.

I agree, but how would we do it? Maybe just enable it manually during the activation of the user account. Or is there a configuration to set the default somewhere?

**Comment by olafgrabienski** [comment]
> Sent a test message also.

Arrived!

**Comment by olafgrabienski** [comment]
> Or is there a configuration to set the default somewhere?

Oh yes, it is, and it was already selected: "Enable the personal contact form by default for new users."

The setting "will not affect existing users". So, I'm going to update the user accounts, to have all accounts the same setting (personal contact form enabled).

**Comment by olafgrabienski** [comment]
> have all accounts the same setting (personal contact form enabled)

Done!

**Comment by robertgarrigos** [comment]
Thanks!
