### ISSUE TITLE
Make a Drupal version of the Borg theme

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/localization#37]
I have long been wanting to make a drupal version of the Borg theme we use on b.org. Primarily for this site, but also because I think it would be cool to contribute back to Drupal. I'm assigning this issue to myself since I had planned to do it, but if anyone else wants to give it a go, please leave a comment here and we can discuss :)

**Comment by olafgrabienski** [comment]
If it was 'only' for the localization site, I guess making a sub theme of *Responsive Bartik* and providing some CSS could be sufficient. A proper theme sounds however interesting!

**Comment by olafgrabienski** [comment]
In the meantime, the Translation site is running on Backdrop (https://github.com/backdrop-ops/localize.backdropcms.org/issues/45) . If a Drupal version of the Borg theme is still of interest, let's discuss it somewhere else.
