### ISSUE TITLE
Registration of user account doesn't work well

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-ops/localization#39]
Reported by @indigoxela [via Zulip](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Translation.20concept.20%28server%29/near/205355740):

I may register but email verification is off and I couldn't set my password either when registering. Now I get a mail that my account has been unblocked but I actually have to "reset" my password first because I never was able to set it...
Ah, wait, I can't reset my pw either ... neither with username nor with email - unknown...

**Comment by olafgrabienski** [comment]
Current settings on `admin/people/config/accounts` look okay:

- Who can register accounts?
Visitors, but administrator approval is required
- Require e-mail verification when a visitor creates an account.
Enabled

**Comment by olafgrabienski** [comment]
Not able to reproduce the issue: I've registered a test account, and everything worked as expected, including email notifications about pending and activated account.

Well, it's not yet confirmed but I guess I may have simply forgotten to set the account status to "Active" for the registration mentioned above (just saved the account page without any change and sent then a welcome message).

**Comment by indigoxela** [comment]
Yep, I think you can close this. The actual problem was that my account wasn't activated but you already sent me a mail (via contact form) telling me you did. Admin in a rush... :wink:

I received the proper mail with pw reset link today and was able to set my pw (account was active).

**Comment by olafgrabienski** [comment]
Good to know that it wasn't a technical issue, thanks for the confirmation! (Closing issue.)
