### ISSUE TITLE
Add backdrop favicon to website

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-ops/localization#44]
Currently this site has the default Drupal favicon.  While I appreciate that moving the site to backdrop CMS is a complex task, at least this will not make it completely obvious that one of our sites is not Backdrop.
Links to #37 but can be done before that as a quick win.

**Comment by jenlampton** [comment]
I've pulled a favicon from backdropcms.org, and updated settings to point to the new icon.
